export const cuisineList = [
  'Solar panels',
  'Wind turbines',
  'Hydroelectric generators',
  'Geothermal systems',
  'Bioenergy systems',
  'Tidal energy converters',
  'Wave energy devices',
  'Solar water heaters',
  'Biomass boilers',
  'Micro hydro turbines',
  'Solar air heaters',
  'Ground source heat pumps',
  'Anaerobic digesters',
  'Solar cookers',
  'Solar dryers',
  'Wind-powered water pumps',
  'Solar-powered lights',
  'Solar-powered chargers',
  'Biogas stoves',
  'Solar ovens',
  'Wind-powered irrigation systems',
  'Solar-powered water purifiers',
  'Biogas lamps',
  'Hybrid renewable energy systems',
  'Solar-powered refrigerators',
  'Solar-powered fans',
  'Solar-powered air conditioners',
  'Solar-powered vehicles',
  'Solar-powered boats',
  'Solar-powered drones',
  'Solar-powered backpacks',
  'Solar-powered watches',
  'Solar-powered calculators',
  'Solar-powered radios',
  'Solar-powered tents',
  'Solar-powered fountains',
  'Solar-powered signs',
  'Solar-powered cameras',
  'Solar-powered streetlights',
  'Solar-powered toys',
  'Solar-powered phone chargers',
  'Wind-powered vehicles',
  'Wind-powered boats',
  'Wind-powered drones',
  'Wind-powered pumps',
  'Wind-powered lights',
  'Hydrogen fuel cells',
  'Hydrogen fuel cell vehicles',
  'Hydrogen fuel cell generators',
  'Hydrogen fuel cell drones',
  'Hydrogen fuel cell boats',
  'Hydrogen fuel cell backup power systems',
  'Hydrogen fuel cell buses',
  'Hydrogen fuel cell forklifts',
  'Hydrogen fuel cell scooters',
  'Hydrogen fuel cell trains',
  'Hydrogen fuel cell trucks',
  'Hydrogen fuel cell motorcycles',
  'Hydrogen fuel cell aircraft',
  'Hydrogen fuel cell bicycles',
  'Hydrogen fuel cell power banks',
  'Hydrogen fuel cell laptops',
  'Hydrogen fuel cell smartphones',
  'Geothermal heat pumps',
  'Geothermal power plants',
  'Geothermal cooling systems',
  'Geothermal greenhouse heaters',
  'Geothermal snow melt systems',
  'Geothermal spas',
  'Geothermal swimming pool heaters',
  'Geothermal hot tubs',
  'Geothermal radiant floor heating systems',
  'Geothermal desalination plants',
  'Geothermal beer brewing systems',
  'Geothermal food drying systems',
  'Geothermal laundry systems',
  'Geothermal timber drying systems',
  'Geothermal fish farming systems',
  'Geothermal poultry farming systems',
  'Geothermal aquaculture systems',
  'Geothermal fruit drying systems',
  'Geothermal vegetable drying systems',
  'Geothermal seaweed farming systems',
  'Geothermal algae farming systems',
  'Geothermal oil extraction systems',
  'Geothermal wine fermentation systems',
  'Geothermal mushroom farming systems',
  'Geothermal tea drying systems',
  'Geothermal coffee drying systems',
  'Geothermal spice drying systems',
  'Geothermal herb drying systems',
  'Geothermal nut drying systems',
  'Geothermal seed drying systems',
  'Geothermal grain drying systems',
  'Geothermal hops drying systems',
  'Geothermal tobacco drying systems',
  'Geothermal medicinal herb drying systems',
  'Geothermal tobacco curing systems',
  'Geothermal medicinal herb curing systems',
  'Geothermal agricultural irrigation systems',
  'Geothermal greenhouse irrigation systems',
  'Geothermal aquaponic systems',
  'Geothermal hydroponic systems',
  'Geothermal desalination systems',
  'Geothermal water heating systems',
  'Geothermal space heating systems',
  'Geothermal power generation systems',
  'Geothermal district heating systems',
  'Geothermal absorption chillers',
  'Geothermal heat exchangers',
  'Geothermal pumps',
  'Geothermal valves',
  'Geothermal heat pipes',
  'Geothermal fans',
  'Geothermal blowers',
  'Geothermal compressors',
  'Geothermal turbines',
  'Geothermal inverters',
  'Geothermal controllers',
  'Geothermal sensors',
  'Geothermal meters',
  'Geothermal switches',
  'Geothermal transformers',
  'Geothermal reactors',
  'Geothermal storage systems',
  'Geothermal batteries',
  'Geothermal capacitors',
  'Geothermal power cables',
  'Geothermal circuit breakers',
  'Geothermal insulators',
  'Geothermal conductors',
  'Geothermal cables',
  'Geothermal connectors',
  'Geothermal relays',
  'Geothermal resistors',
  'Geothermal semiconductors',
  'Geothermal transistors',
  'Geothermal diodes',
  'Geothermal LEDs',
  'Geothermal photovoltaic panels',
  'Geothermal mirrors',
  'Geothermal lenses',
  'Geothermal reflectors',
  'Geothermal absorbers',
  'Geothermal concentrators',
  'Geothermal diffusers',
  'Geothermal collectors',
  'Geothermal evaporators',
  'Geothermal tubes',
  'Geothermal pipes',
  'Geothermal tanks',
  'Geothermal reservoirs',
];

